name: Pull Request Validation
on:
  pull_request:
    branches:
      - master
jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - uses: bahmutov/npm-install@v1
      # - run: yarn lint
      # - run: yarn test --coverage
      # - run: bash <(curl -s https://codecov.io/bash)
      # - run: yarn build
